name: Build and publish npm packages
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
jobs:
  check-build-push-clients:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for changes
        id: vars
        run: |
          echo "::set-output name=has-changes::$(bin/check-changes.sh)"
      - if: '!${{ steps.vars.outputs.has-changes }}'
        run: echo "Skipping building packages"
      - uses: actions/setup-node@v2
        if: '${{ steps.vars.outputs.has-changes }}'
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@redkubes'
      - name: Build and publish clients
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: '${{ steps.vars.outputs.has-changes }}'
        run: |
          sudo apt-get install moreutils
          bin/generate-all.sh
          bin/release-all.sh
