name: Build and publish npm packages
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check for changes
        id: vars
        run: |
          if bin/diff-changes.sh; then
            echo "Changes found, continuing with next step."
            echo "::set-output name=hasdiff::1"
          else
            echo "No changes found, skipping!"
            echo "::set-output name=hasdiff::0"
          fi
  build-push-clients:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ jobs.check.steps.vars.outputs.hasdiff }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@redkubes'
      - name: Build and publish clients
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get install moreutils
          bin/generate-all.sh
          bin/release-all.sh
